const searchInput = document.getElementById("searchInput");
const searchResults = document.getElementById("searchResults");
const faqLinks = document.getElementById("faqLinks");
const searchResultsList = document.getElementById("searchResultsList");

const faqData = [
    { title: "Delta Airlines Stock", url: "https://www.faresmatch.com/faq/how-much-is-delta-airlines-stock.aspx" },
    { title: "Delta Airlines Based", url: "https://www.faresmatch.com/faq/where-is-delta-airlines-based.aspx" },
    { title: "United Airlines Flights to Reno", url: "https://www.faresmatch.com/faq/how-to-book-united-airlines-flights-to-reno.aspx" },
    { title: "Delta Airlines Partner Information", url: "https://www.faresmatch.com/faq/what-are-delta-airlines-partners.aspx" },
    { title: "Delta Airlines-What is It and History to Know", url: "https://www.faresmatch.com/faq/what-is-delta-airlines.aspx" },
    { title: "How to Get Cheap Flights to Detroit?", url: "https://www.faresmatch.com/faq/how-to-get-cheap-flights-to-detroit.aspx" },
    { title: "Cheap Flights-When to Book Tickets at the Lowest Cost?", url: "https://www.faresmatch.com/faq/cheap-flights-when-to-book.aspx" },
    { title: "Can You Still Get Discount on Cheap Flights for Funeral?", url: "https://www.faresmatch.com/faq/how-to-get-cheap-flights-for-funeral.aspx" },
    { title: "Easy Steps to Calculate Cheap Flights NYC to Europe", url: "https://www.faresmatch.com/faq/how-to-calculate-cheap-flights-nyc-to-europe.aspx" },
    { title: "How to Get Cheap Flights Tickets from Oahu to Japan?", url: "https://www.faresmatch.com/faq/how-to-get-cheap-flights-from-oahu-to-japan.aspx" },
    { title: "Cheap Vegas Show Tickets", url: "https://www.faresmatch.com/faq/how-to-get-cheap-vegas-show-tickets.aspx" },
    { title: "How to Get First Class Tickets Cheap?", url: "https://www.faresmatch.com/faq/how-to-get-first-class-tickets-cheap.aspx" },
    { title: "When to Find Cheap Flights?", url: "https://www.faresmatch.com/faq/when-to-find-cheap-flights.aspx" },
    { title: "Best Time to Check for Cheap Flights", url: "https://www.faresmatch.com/faq/what-is-the-best-time-to-check-for-cheap-flights.aspx" },
    { title: "When Flights Are Cheaper to San Francisco from NYC", url: "https://www.faresmatch.com/faq/when-are-cheap-flights-to-san-francisco-from-nyc.aspx" },
    { title: "What do First Class Flights?", url: "https://www.faresmatch.com/faq/what-do-first-class-flights-look-like.aspx" },
    { title: "How Much is First Class Flights?", url: "https://www.faresmatch.com/faq/how-much-is-first-class-flights.aspx" },
    { title: "What Comes with First Class Flights?", url: "https://www.faresmatch.com/faq/what-comes-with-first-class-flights.aspx" },
    { title: "How to Get Cheap First Class Tickets?", url: "https://www.faresmatch.com/faq/how-to-get-cheap-first-class-tickets.aspx" },
    { title: "How to Get LastMinute Flights to Los Angeles?", url: "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-los-angeles.aspx" },
    { title: "How to Get Cheap Delta Flights?", url: "https://www.faresmatch.com/faq/how-to-get-cheap-delta-flights.aspx" },
    { title: "How to Get Last Minute Flights to Arizona?", url: "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-arizona.aspx" },
    { title: "How to Get Last Minute Flights to Austin? ", url: "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-austin.aspx" },
    { title: "How to Get Last-Minute Flights to Chicago?", url: "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-chicago.aspx" },
    { title: "How to Find Cheap Flights to Europe?", url: "https://www.faresmatch.com/faq/how-to-find-cheap-flights-to-europe.aspx" },
    { title: "How to Find Cheap Flights to Hawaii?", url: "https://www.faresmatch.com/faq/how-to-find-cheap-flights-to-hawaii.aspx" },
    { title: "How to Find Cheap Flights Without Destination?", url: "https://www.faresmatch.com/faq/how-to-find-cheap-flights-without-destination.aspx" },
    { title: "How to Fly First Class for the Price of Economy?", url: "https://www.faresmatch.com/faq/how-to-fly-first-class-for-the-price-of-economy.aspx" },
    { title: "What is Economy Class on Plane?", url: "https://www.faresmatch.com/faq/what-is-economy-class-on-plane.aspx" },
    { title: "March is Time to Get Cheap Flights to Fort Lauderdale", url: "https://www.faresmatch.com/faq/when-to-get-cheap-flights-to-fort-lauderdale.aspx" },
    { title: "Where to Buy Cheap Disney Tickets", url: "https://www.faresmatch.com/faq/where-to-buy-cheap-disney-tickets.aspx" },
    { title: "Get Cheap Concert Tickets Last Minute", url: "https://www.faresmatch.com/faq/how-to-get-cheap-concert-tickets-last-minute.aspx" },
    { title: "Cheap Airline Tickets", url: "https://www.faresmatch.com/faq/how-do-you-get-cheap-airline-tickets.aspx" },
    { title: "How Far in Advance Can I Book a Flight", url: "https://www.faresmatch.com/faq/how-far-in-advance-can-i-book-a-flight.aspx" },
    { title: "How to Book a Flight Ticket?", url: "https://www.faresmatch.com/faq/how-to-book-a-flight-ticket.aspx" },
    { title: "How to Book a Flight?", url: "https://www.faresmatch.com/faq/how-to-book-a-flight.aspx" },
    { title: "How to Find Cheap Flight Tickets?", url: "https://www.faresmatch.com/faq/how-to-find-cheap-flight-tickets.aspx" },
    { title: "How to Get Cheap Plane Tickets Online", url: "https://www.faresmatch.com/faq/how-to-get-cheap-plane-tickets.aspx" },
    { title: "How to Book Flight Ticket Online?", url: "https://www.faresmatch.com/faq/how-to-book-flight-ticket-online.aspx" },
    { title: "How to Book Online Ticket?", url: "https://www.faresmatch.com/faq/how-to-book-online-ticket.aspx" },
    { title: "How to Get Cheap First Class Tickets?", url: "https://www.faresmatch.com/faq/how-to-get-cheap-first-class-tickets.aspx" },
    { title: "How to Fly Comfortably in Economy Class?", url: "https://www.faresmatch.com/faq/how-to-fly-comfortably-in-economy-class.aspx" },
    { title: "How to Buy Cheap Plane Tickets", url: "https://www.faresmatch.com/faq/how-to-buy-cheap-plane-tickets.aspx" },
    { title: "How to Book a Airlines Flight Ticket?", url: "https://www.faresmatch.com/faq/how-to-book-a-flight-ticket.aspx" },
    { title: "How to Get Cheap First Class Flights Tickets?", url: "https://www.faresmatch.com/faq/how-to-get-cheap-first-class-flight-tickets.aspx" },
  { "url": "https://www.faresmatch.com/faq/reddit-how-to-find-cheap-flights.aspx", "title": "Reddit How to Find Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/why-are-flights-so-cheap-right-now.aspx", "title": "Why Are Flights So Cheap Right Now" },
  { "url": "https://www.faresmatch.com/faq/what-is-premium-economy-class.aspx", "title": "What is Premium Economy Class?" },
  { "url": "https://www.faresmatch.com/faq/when-to-book-cheap-flights.aspx", "title": "When to Book Cheap Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-boise.aspx", "title": "United Airlines Flights to Boise" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-missouri.aspx", "title": "United Airlines Flights to Missouri" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-grand-rapids.aspx", "title": "United Airlines Flights to Grand Rapids" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-kalispell.aspx", "title": "United Airlines Flights to Kalispell" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-kansas-city.aspx", "title": "Book Tickets of Kansas City" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-las-vegas.aspx", "title": "Book Tickets of Las Vegas" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-newark.aspx", "title": "Manage Booking of Newark" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-omaha.aspx", "title": "Book United Airlines Flights to Omaha" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-nebraska.aspx", "title": "Book Tickets of United Airlines Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-florida.aspx", "title": "Travel Around Florida" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-spokane.aspx", "title": "Fly for Spokane" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-state-college.aspx", "title": "Book Tickets of State College" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-santa-maria.aspx", "title": "Allegiant Airlines Tickets to Santa Maria" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-georgia.aspx", "title": "Georgia Flights Booking with Allegiant Airlines" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-illinois.aspx", "title": "Book Illinois Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-indiana.aspx", "title": "Indiana Flights Travel" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-st-cloud.aspx", "title": "Allegiant Airlines Tickets to St Cloud" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-airline-tickets.aspx", "title": "How to Find Cheap Airline Tickets?" },
  { "url": "https://www.faresmatch.com/faq/how-to-buy-cheap-flight-tickets.aspx", "title": "How to Buy Cheap Flight Tickets?" },
  { "url": "https://www.faresmatch.com/faq/what-is-the-best-day-to-check-cheap-flights.aspx", "title": "What is the Best Day to Check Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-disney-tickets.aspx", "title": "How to Get Cheap Disney Tickets?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-delta-international-flights.aspx", "title": "Book Cheap Delta International Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-business-class-tickets.aspx", "title": "How to Get Cheap Business Class Tickets?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-airline-tickets.aspx", "title": "Ideas to Get Cheap Airline Tickets" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-last-minute-flights.aspx", "title": "How to Find Cheap Last Minute Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-flights-to-anywhere.aspx", "title": "How to Find Cheap Flights to Anywhere?" },
  { "url": "https://www.faresmatch.com/faq/when-time-is-the-cheap-flights-from-hyderabad-to-maldives-in-december.aspx", "title": "Cheapest Flights from Hyderabad to Maldives" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-flights-from-slc-to-fll.aspx", "title": "Find Cheap Flights from SLC to FLL" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-flights.aspx", "title": "How to Find Cheap Flights Guide" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-disney-world-tickets.aspx", "title": "Few Things to Know About Cheap Disney World Tickets" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-flights-for-new-years.aspx", "title": "Cheap Flights for New Years" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-first-class-flights.aspx", "title": "How to Book First Class Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-first-class-flights.aspx", "title": "How to Get Cheap First-Class Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-upgrade-from-economy-to-business-class.aspx", "title": "How to Upgrade from Economy to Business Class?" },
  { "url": "https://www.faresmatch.com/faq/why-is-so-hard-for-military-to-get-cheap-flights.aspx", "title": "Is It Hard for Military to Get Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/what-do-you-get-in-first-class-flights.aspx", "title": "What do You Get in First Class Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-a-plane-ticket.aspx", "title": "How to Book A Plane Ticket?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-fort-worth.aspx", "title": "How to Get Last Minute Flights to Fort Worth?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-houston.aspx", "title": "How to Get Last-Minute Flights to Houston?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-illinois.aspx", "title": "How to Get LastMinute Flights to Illinois?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-san-jose.aspx", "title": "How to Get Last Minute Flights to San Jose?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-new-york.aspx", "title": "How to Get LastMinute Flights to New York?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-a-flight-ticket.aspx", "title": "How to Book a Flight Ticket?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-cheap-last-minute-flights.aspx", "title": "How to Book Cheap Last-Minute Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-business-class-flights.aspx", "title": "How to Find Cheap Business Class Flights? " },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-first-class-flights.aspx", "title": "How to Find Cheap First-Class Flights?" },
  { "url": "https://www.faresmatch.com/faq/where-to-find-cheap-flights.aspx", "title": "Where to Find Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-search-flights-to-anywhere.aspx", "title": "How to Search Cheap Flights to Anywhere?" },
  { "url": "https://www.faresmatch.com/faq/how-to-buy-cheap-airline-tickets.aspx", "title": "How to Buy Cheap Airline Tickets?" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-tickets.aspx", "title": "How to Find Cheap Tickets?" },
  { "url": "https://www.faresmatch.com/faq/where-to-buy-cheap-flight-tickets.aspx", "title": "Where to Buy Cheap Flight Tickets?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-disneyland-tickets.aspx", "title": "Get Cheap Disneyland Tickets" },
  { "url": "https://www.faresmatch.com/faq/what-info-do-you-need-to-book-a-flight.aspx", "title": "What Info Do You Need to Book a Flight?" },
  { "url": "https://www.faresmatch.com/faq/what-is-the-best-day-to-book-a-flight.aspx", "title": "What is Best Day to Book a Flight?" },
  { "url": "https://www.faresmatch.com/faq/what-is-the-cheapest-day-to-book-a-flight.aspx", "title": "What isthe Cheapest Day to Book a Flight?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-lion-king-broadway-tickets.aspx", "title": "How to get Cheap Lion King Broadway Tickets?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-international-flights.aspx", "title": "How to Get Cheap International Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-flights-to-vietnam.aspx", "title": "How to Get Cheap Flights to Vietnam" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-flights-to-vegas.aspx", "title": "How to Get Cheap Flights to Vegas?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-cheap-flights.aspx", "title": "How to Get Last Minute Cheap Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-really-cheap-flights.aspx", "title": "How to Get Really Cheap Flights" },
  { "url": "https://www.faresmatch.com/faq/when-to-buy-cheap-flights.aspx", "title": "When to Buy Cheap Flights" },
  { "url": "https://www.faresmatch.com/faq/when-to-get-cheap-flights.aspx", "title": "When to Get Cheap Flights" },
  { "url": "https://www.faresmatch.com/faq/where-can-i-find-cheap-flights.aspx", "title": "Where Can I Find Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-airlines-to-des-moines.aspx", "title": "Book Des Moines Travel" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-airlines-to-detroit.aspx", "title": "United Airlines Flights to Detroit" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-airlines-to-billings.aspx", "title": "United Airlines Flights to Billings" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-airlines-to-boston.aspx", "title": "Find Deals of United Airlines Flights to Boston" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-manchester.aspx", "title": "Discount on All Manchester Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-traverse-city.aspx", "title": "United Airlines Flights to Traverse City" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-montana.aspx", "title": "Book Tickets of Montana" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-rochester.aspx", "title": "Book Rochester Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-new-jersey.aspx", "title": "Book New Jersey Flights Along with United Airlines Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-new-mexico.aspx", "title": "Avail Deals of United Airlines Flights to New Mexico" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-wichita.aspx", "title": "Wichita Travel is Discounted Now" },
  { "url": "https://www.faresmatch.com/faq/delta-airlines-what-can-i-bring.aspx", "title": "Delta Airlines What Can You Bring?" },
  { "url": "https://www.faresmatch.com/faq/how-many-bags-are-free-on-delta-airlines.aspx", "title": "Free Baggage Policy of Delta Airlines" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-toledo.aspx", "title": "Book Tickets of Toledo" },
  { "url": "https://www.faresmatch.com/faq/how-do-i-print-out-my-boarding-pass-for-delta-airlines.aspx", "title": "Print Boarding Pass for Delta Airlines" },
  { "url": "https://www.faresmatch.com/faq/how-safe-is-delta-airlines.aspx", "title": "Delta Airlines Safety Measures and Information" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-ohio.aspx", "title": "Ohio Travel Discount" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-pennsylyvania.aspx", "title": "Pennsylvania Allegiant Airlines" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-louisiana.aspx", "title": "Louisiana Travel" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-rochester.aspx", "title": "Book Rochester Flight Tickets" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-sioux-falls.aspx", "title": "Allegiant Airlines Tickets to Sioux Falls" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-south-bend.aspx", "title": "Allegiant Airlines Tickets to South Bend" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-south-dakota.aspx", "title": "Allegiant Airlines Tickets to South Dakota" },
  { "url": "https://www.faresmatch.com/faq/cheap-flights-how-to-find.aspx", "title": "Cheap Flights How to Find?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-cheap-flights.aspx", "title": "How to Book Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-buy-cheap-flights.aspx", "title": "How to Buy Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-flights-last-minute.aspx", "title": "How to Get Cheap Flights Last Minute?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-flights-los-angeles-to-seattle.aspx", "title": "Cheap Flights Los Angeles to Seattle" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-last-minute-flights.aspx", "title": "How to Get Cheap Last-Minute Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-universal-tickets.aspx", "title": "Read Before Buy Cheap Universal Tickets" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-flights-tickets.aspx", "title": "How to Get Cheap Flights Tickets?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-flights.aspx", "title": "How to Get Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-cheap-flights-vpn.aspx", "title": "How to Get Cheap Flights VPN?" },
  { "url": "https://www.faresmatch.com/faq/how-to-find-cheap-flexible-flights.aspx", "title": "5 Things to Know, to Find Cheap Flexible Fights" },
  { "url": "https://www.faresmatch.com/faq/what-is-economy-coach-class.aspx", "title": "What is Economy Coach Class?" },
  { "url": "https://www.faresmatch.com/faq/why-are-flights-cheap-to-ireland-in-march.aspx", "title": "Why Are Flights Cheap to Ireland in March" },
  { "url": "https://www.faresmatch.com/faq/why-are-spirit-flights-so-cheap.aspx", "title": "Why Are Spirit Flights So Cheap" },
  { "url": "https://www.faresmatch.com/faq/why-cant-you-find-cheap-flights-on-airline-site.aspx", "title": "Can You Find Cheap Flights on Airline Site?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-an-airline-ticket-online.aspx", "title": "How to Book an Airline Ticket Online?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-delta-companion-ticket.aspx", "title": "How to Book Delta Companion Ticket?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-a-ticket-online.aspx", "title": "How to Book a Ticket Online?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-pennsylvania.aspx", "title": "How to Get Last Minute Flights to Pennsylvania?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-philadelphia.aspx", "title": "How to Get Last Minute Flights to Philadelphia?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-phoenix.aspx", "title": "How to Get Last Minute Flights to Phoenix?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-last-minute-flights-to-san-antonio.aspx", "title": "How to Get Last Minute Flights to San Antonio?" },
  { "url": "https://www.faresmatch.com/faq/how-can-i-find-cheap-flights.aspx", "title": "How Can I Find Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-can-i-get-cheap-flights.aspx", "title": "How Can I Get Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-do-i-get-cheap-flights.aspx", "title": "How Do I Get Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-much-are-first-class-flights.aspx", "title": "How Much Are First Class Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-much-extra-is-first-class-flights.aspx", "title": "How Much Extra is First Class Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-a-companion-ticket-on-delta.aspx", "title": "How to Book a Companion Ticket on Delta?" },
  { "url": "https://www.faresmatch.com/faq/when-is-the-best-time-to-book-a-flight.aspx", "title": "When is the Best Time to Book a Flight?" },
  { "url": "https://www.faresmatch.com/faq/when-to-buy-cheap-flight-tickets.aspx", "title": "When to Buy Cheap Flight Tickets?" },
  { "url": "https://www.faresmatch.com/faq/where-can-i-buy-cheap-airline-tickets.aspx", "title": "Where Can I Buy Cheap Airline Tickets?" },
  { "url": "https://www.faresmatch.com/faq/where-to-buy-cheap-disneyland-tickets.aspx", "title": "Where to Buy Cheap Disneyland Tickets" },
  { "url": "https://www.faresmatch.com/faq/where-to-get-cheap-airline-tickets.aspx", "title": "Where to Get Cheap Airline Tickets? " },
  { "url": "https://www.faresmatch.com/faq/where-to-buy-cheap-plane-tickets.aspx", "title": "Where to Buy Cheap Plane Tickets?" },
  { "url": "https://www.faresmatch.com/faq/where-to-find-cheap-airline-tickets.aspx", "title": "Where to Find Cheap Airline Tickets?" },
  { "url": "https://www.faresmatch.com/faq/how-to-buy-broadway-tickets-cheap.aspx", "title": "Broadway Tickets Cheap-How to Buy This?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-ticket.aspx", "title": "How to Book Ticket?" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-super-cheap-flights.aspx", "title": "How to Get Super Cheap Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-get-universal-studios-tickets-cheap.aspx", "title": "How to Get Universal Studios Tickets Cheap?" },
  { "url": "https://www.faresmatch.com/faq/how-to-search-for-cheap-flights.aspx", "title": "How to Search for Cheap Flights" },
  { "url": "https://www.faresmatch.com/faq/where-can-i-get-cheap-flights.aspx", "title": "Where Can I Get Cheap Flights?" },
  { "url": "https://www.faresmatch.com/faq/where-to-book-cheap-flights.aspx", "title": "Where to Book Cheap Flights Online?" },
  { "url": "https://www.faresmatch.com/faq/which-airline-has-the-widest-seats-in-economy-class.aspx", "title": "Which Airline Has the Widest Seats in Economy Class?" },
  { "url": "https://www.faresmatch.com/faq/who-has-the-best-first-class-flights.aspx", "title": "Who Has the Best First-Class Flights?" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-airlines-to-duluth.aspx", "title": "Book the tickets of Duluth" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-airlines-to-bozeman.aspx", "title": "United Airlines Flights Discount to Know" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-chicago.aspx", "title": "United Airlines Flights to Chicago" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-airlines-to-kansas.aspx", "title": "United Airlines Flights to Kansas" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-minnesota.aspx", "title": "Find United Airlines Flights to Minnesota" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-minneapolis.aspx", "title": "Book Minneapolis Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-michigan.aspx", "title": "Michigan Travel with United Airlines Flights" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-united-flights-to-new-hampshire.aspx", "title": "United Airlines Flights to New Hampshire" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-west-palm-beach.aspx", "title": "West Palm Beach Vacations Discount" },
  { "url": "https://www.faresmatch.com/faq/where-are-delta-airlines-hubs.aspx", "title": "Information About Delta Airlines Hubs" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-tulsa.aspx", "title": "Book Tickets of Tulsa" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-washington-dc.aspx", "title": "Book Washington DC Travel" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-kansas.aspx", "title": "Kansas Vacations" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-stockton.aspx", "title": "Book Travel of Stockton" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-syracuse.aspx", "title": "Save More on Allegiant Airlines Tickets to Syracuse" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-springfield.aspx", "title": "Springfield Travel Discount" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-california.aspx", "title": "Travel for California" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-new-york.aspx", "title": "Book New York Vacations Tickets" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-san-antonio.aspx", "title": "Allegiant Airlines Tickets to San Antonio" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-san-diego.aspx", "title": "Allegiant Airlines Tickets to San Diego" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-texas.aspx", "title": "Allegiant Airlines Tickets to Texas" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-sarasota.aspx", "title": "Allegiant Airlines Tickets to Sarasota" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-savannah.aspx", "title": "Allegiant Airlines Tickets to Savannah" },
  { "url": "https://www.faresmatch.com/faq/how-to-book-allegiant-airlines-tickets-to-shreveport.aspx", "title": "Allegiant Airlines Tickets to Shreveport" }
];

searchInput.addEventListener("input", function () {
    const searchTerm = searchInput.value.trim().toLowerCase();
    searchResultsList.innerHTML = ""; // Clear previous results

    if (searchTerm !== "") {
        const filteredResults = faqData.filter(faq =>
            faq.title.toLowerCase().includes(searchTerm)
        );

        if (filteredResults.length > 0) {
            filteredResults.forEach(result => {
                const listItem = document.createElement("li");
                const link = document.createElement("a");
                link.href = result.url;
                link.textContent = result.title;
                listItem.appendChild(link);
                searchResultsList.appendChild(listItem);
            });
        } else {
            searchResultsList.innerHTML = "<li>No results found.</li>";
        }

        searchResults.style.display = "block";
        faqLinks.style.display = "none";
    } else {
        searchResults.style.display = "none";
        faqLinks.style.display = "grid";
    }
});

document.getElementById("searchForm").addEventListener('submit', function (e) {
    e.preventDefault();
});